apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.backend.databaseURL }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.backend.databaseUsername }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.backend.databasePassword }}
