apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  pg_hba.conf: |
    # Allow all IPv4 connections
    host    all             all             0.0.0.0/0               md5
    # Allow all IPv6 connections
    host    all             all             ::/0                    md5
    # Allow local connections
    local   all             all                                     trust