
database:
  image: "postgres:latest"
  replicas: 1
  storageSize: "10Gi"
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "nouhaila"
    POSTGRES_DB: "postgres"

frontend:
  image: "nouhabk23/frontend-image-final:1.0.1"
  replicas: 1

backend:
  image: "nouhabk23/backend-image-final:1.0.3"
  replicas: 1
  databaseURL: "jdbc:postgresql://database:5432/postgres"
  databaseUsername: "postgres"
  databasePassword: "nouhaila"
