
database:
  image: "postgres:latest"
  replicas: 1
  storageSize: "10Gi"
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "nouhaila"
    POSTGRES_DB: "projet"

frontend:
  image: "localhost:7000/frontend-image-final:1.0.0"
  replicas: 1

backend:
  image: "localhost:7000/backend-image-final:1.0.0"
  replicas: 1
  databaseURL: "jdbc:postgresql://database:5432/projet"
  databaseUsername: "user"
  databasePassword: "password"
